name: http_client_inspector
description: 'A package to inspect http client package requests and responses in Flutter directly in your App.'
version: 0.0.2
repository: 'https://github.com/Chonli/http_inspector'

environment:
  sdk: ^3.10.0
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  mocktail: ^1.0.4
